"""Scalping strategy engine that orchestrates signal generation and trade decisions.

Combines technical indicators to produce entry/exit signals for
Nifty50 options (calls and puts).
"""

import logging
from dataclasses import dataclass
from datetime import datetime
from typing import Optional

import pandas as pd

from scalper.config import StrategyConfig
from scalper.indicators import (
    Signal,
    aggregate_signals,
    get_ema_signal,
    get_rsi_signal,
    get_supertrend_signal,
    get_vwap_signal,
)

logger = logging.getLogger(__name__)


@dataclass
class TradeSignal:
    """A trade signal generated by the strategy engine."""
    timestamp: datetime
    direction: Signal          # BULLISH or BEARISH
    option_type: str           # CE or PE
    strength: int              # Number of confirming signals
    signals_detail: dict       # Individual signal breakdown
    spot_price: float
    reason: str


class ScalpingStrategy:
    """Options scalping strategy based on multiple technical indicators.

    Generates CALL (CE) signals on bullish confluence and
    PUT (PE) signals on bearish confluence.

    Entry conditions (configurable min_signals_for_entry):
    - EMA crossover (fast > slow = bullish)
    - RSI (oversold = bullish, overbought = bearish)
    - Price vs VWAP (above = bullish, below = bearish)
    - SuperTrend direction (up = bullish, down = bearish)
    """

    def __init__(self, config: StrategyConfig):
        self.config = config
        self._last_signal: Optional[TradeSignal] = None
        self._cooldown_candles = 3  # Min candles between signals
        self._candle_count_since_signal = 999

    def evaluate(self, candle_data: pd.DataFrame, spot_price: float) -> Optional[TradeSignal]:
        """Evaluate current market data and generate a trade signal if conditions met.

        Args:
            candle_data: OHLCV DataFrame with at least 30 candles.
            spot_price: Current Nifty spot price.

        Returns:
            TradeSignal if entry conditions are met, None otherwise.
        """
        if candle_data.empty or len(candle_data) < max(
            self.config.ema_slow_period + 5,
            self.config.rsi_period + 5,
            self.config.supertrend_period + 5,
        ):
            logger.debug("Insufficient candle data: %d candles", len(candle_data))
            return None

        self._candle_count_since_signal += 1

        # Cooldown check
        if self._candle_count_since_signal < self._cooldown_candles:
            return None

        close = candle_data["close"]
        signals_detail = {}

        # 1. EMA Crossover Signal
        ema_signal = get_ema_signal(
            close,
            self.config.ema_fast_period,
            self.config.ema_slow_period,
        )
        signals_detail["ema"] = ema_signal.value

        # 2. RSI Signal
        rsi_signal = get_rsi_signal(
            close,
            self.config.rsi_period,
            self.config.rsi_overbought,
            self.config.rsi_oversold,
        )
        signals_detail["rsi"] = rsi_signal.value

        # 3. VWAP Signal
        vwap_signal = Signal.NEUTRAL
        if self.config.use_vwap:
            vwap_signal = get_vwap_signal(candle_data)
        signals_detail["vwap"] = vwap_signal.value

        # 4. SuperTrend Signal
        st_signal = get_supertrend_signal(
            candle_data,
            self.config.supertrend_period,
            self.config.supertrend_multiplier,
        )
        signals_detail["supertrend"] = st_signal.value

        all_signals = [ema_signal, rsi_signal, vwap_signal, st_signal]
        final_signal = aggregate_signals(all_signals, self.config.min_signals_for_entry)

        if final_signal == Signal.NEUTRAL:
            return None

        # Count confirming signals
        if final_signal == Signal.BULLISH:
            strength = sum(1 for s in all_signals if s == Signal.BULLISH)
            option_type = "CE"
            reason_parts = [
                name for name, val in signals_detail.items() if val == "BULLISH"
            ]
            reason = f"BULLISH confluence: {', '.join(reason_parts)}"
        else:
            strength = sum(1 for s in all_signals if s == Signal.BEARISH)
            option_type = "PE"
            reason_parts = [
                name for name, val in signals_detail.items() if val == "BEARISH"
            ]
            reason = f"BEARISH confluence: {', '.join(reason_parts)}"

        trade_signal = TradeSignal(
            timestamp=datetime.now(),
            direction=final_signal,
            option_type=option_type,
            strength=strength,
            signals_detail=signals_detail,
            spot_price=spot_price,
            reason=reason,
        )

        self._last_signal = trade_signal
        self._candle_count_since_signal = 0

        logger.info(
            "SIGNAL: %s | %s | Strength=%d/%d | Spot=%.2f | %s",
            final_signal.value,
            option_type,
            strength,
            len(all_signals),
            spot_price,
            reason,
        )

        return trade_signal

    def should_exit_on_reversal(
        self, candle_data: pd.DataFrame, current_option_type: str
    ) -> bool:
        """Check if strategy signals suggest exiting current position due to reversal.

        Args:
            candle_data: Current OHLCV data.
            current_option_type: Current position type ('CE' or 'PE').

        Returns:
            True if there's a strong reversal signal against current position.
        """
        if candle_data.empty or len(candle_data) < self.config.ema_slow_period + 5:
            return False

        close = candle_data["close"]

        ema_signal = get_ema_signal(
            close,
            self.config.ema_fast_period,
            self.config.ema_slow_period,
        )
        st_signal = get_supertrend_signal(
            candle_data,
            self.config.supertrend_period,
            self.config.supertrend_multiplier,
        )

        # Strong reversal: both EMA and SuperTrend agree on opposite direction
        if current_option_type == "CE":
            if ema_signal == Signal.BEARISH and st_signal == Signal.BEARISH:
                logger.info("Reversal detected against CE position")
                return True
        elif current_option_type == "PE":
            if ema_signal == Signal.BULLISH and st_signal == Signal.BULLISH:
                logger.info("Reversal detected against PE position")
                return True

        return False

    def get_status(self) -> dict:
        """Get current strategy status.

        Returns:
            Dict with strategy state info.
        """
        return {
            "last_signal": (
                {
                    "direction": self._last_signal.direction.value,
                    "option_type": self._last_signal.option_type,
                    "strength": self._last_signal.strength,
                    "spot_price": self._last_signal.spot_price,
                    "time": self._last_signal.timestamp.strftime("%H:%M:%S"),
                    "reason": self._last_signal.reason,
                }
                if self._last_signal
                else None
            ),
            "cooldown_remaining": max(
                0, self._cooldown_candles - self._candle_count_since_signal
            ),
        }
